name: Frontend

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: maximkirsch/partibremendockerhubrepo:web
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
           # Make sure the @v0.9.0 matches the current version of the action
      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_AUTH_KEY }}

      -
        name: prepare ssh
        run:
          mkdir -p ~/.ssh/
      -
        name: keyscan
        run:
          ssh-keyscan -H ${{ secrets.HOSTNAME }} >> ~/.ssh/known_hosts
      -
        name: login server
        run:
          ssh -T ${{ secrets.SSH_USER }}@${{ secrets.HOSTNAME }} "docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} ${{ secrets.REGISTRY_URL }} && docker service update --image maximkirsch/partibremendockerhubrepo:web --with-registry-auth partibremen_web"
